# Generated by Django 5.2 on 2025-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо (ИП)'), ('business', 'Юридическое лицо')], default='business', max_length=20, verbose_name='Тип поставщика')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации / ФИО ИП')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('inn', models.CharField(blank=True, help_text='10 цифр для юр. лиц, 12 цифр для ИП и физ. лиц', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Только для юр. лиц', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('okpo', models.CharField(blank=True, max_length=10, verbose_name='ОКПО')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Название банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('bank_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счет')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_position', models.CharField(blank=True, max_length=200, verbose_name='Должность контактного лица')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон контактного лица')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email контактного лица')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Условия оплаты')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='Условия доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
    ]
