# Generated by Django 5.2 on 2025-04-29 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('individual', 'Индивидуальный предприниматель'), ('business', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип компании')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Название компании / ФИО ИП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('inn', models.CharField(blank=True, help_text='10 цифр для юр. лиц, 12 цифр для ИП', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Только для юр. лиц', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('okpo', models.CharField(blank=True, max_length=10, verbose_name='ОКПО')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Название банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('bank_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счет')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон компании')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email компании')),
                ('website', models.URLField(blank=True, verbose_name='Сайт компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип компании')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company_stamps/', verbose_name='Печать')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company_signatures/', verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
            },
        ),
    ]
