# Generated by Django 5.2 on 2025-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль (₽)'), ('USD', 'Доллар США ($)'), ('EUR', 'Евро (€)'), ('GBP', 'Фунт стерлингов (£)')], default='RUB', max_length=5, verbose_name='Предпочтительная валюта'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsch')], default='ru', max_length=5, verbose_name='Предпочтительный язык'),
        ),
    ]
