# Generated by Django 5.2 on 2025-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_preferred_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('plan_type', models.CharField(choices=[('basic', 'Базовый'), ('professional', 'Профессиональный'), ('enterprise', 'Корпоративный')], default='basic', max_length=20, verbose_name='Тип тарифа')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в год')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный тариф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('max_clients', models.PositiveIntegerField(default=0, help_text='0 означает неограниченное количество', verbose_name='Максимальное количество клиентов')),
                ('feature_invoice_templates', models.BooleanField(default=True, verbose_name='Шаблоны счетов')),
                ('feature_pdf_export', models.BooleanField(default=True, verbose_name='Экспорт PDF')),
                ('feature_basic_analytics', models.BooleanField(default=True, verbose_name='Базовая аналитика')),
                ('feature_custom_templates', models.BooleanField(default=False, verbose_name='Настраиваемые шаблоны')),
                ('feature_auto_reminders', models.BooleanField(default=False, verbose_name='Автоматические напоминания')),
                ('feature_crm_integration', models.BooleanField(default=False, verbose_name='Интеграция с CRM')),
                ('feature_advanced_analytics', models.BooleanField(default=False, verbose_name='Расширенная аналитика')),
                ('feature_priority_support', models.BooleanField(default=False, verbose_name='Приоритетная поддержка')),
                ('feature_special_integrations', models.BooleanField(default=False, verbose_name='Специальные интеграции')),
                ('feature_multi_currency', models.BooleanField(default=False, verbose_name='Мультивалютные счета')),
                ('feature_business_analytics', models.BooleanField(default=False, verbose_name='Бизнес-аналитика')),
                ('feature_multi_user', models.BooleanField(default=False, verbose_name='Управление несколькими пользователями')),
                ('feature_dedicated_manager', models.BooleanField(default=False, verbose_name='Выделенный менеджер')),
                ('feature_api_access', models.BooleanField(default=False, verbose_name='API доступ')),
                ('additional_features', models.JSONField(blank=True, help_text='JSON формат для дополнительных функций', null=True, verbose_name='Дополнительные функции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['order', 'price_monthly'],
            },
        ),
    ]
