# Generated by Django 5.2 on 2025-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricingplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='additional_features',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_api_access',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_auto_reminders',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_basic_analytics',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_business_analytics',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_crm_integration',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_custom_templates',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_dedicated_manager',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_invoice_templates',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_multi_currency',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_multi_user',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_pdf_export',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_priority_support',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='feature_special_integrations',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_yearly',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature_notifications',
            field=models.BooleanField(default=False, verbose_name='Система уведомлений'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature_ocr',
            field=models.BooleanField(default=False, verbose_name='Сканирование документов (OCR)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature_support',
            field=models.BooleanField(default=False, verbose_name='Поддержка'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature_unlimited_documents',
            field=models.BooleanField(default=True, verbose_name='Неограниченное количество документов'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature_watermark_pdf',
            field=models.BooleanField(default=True, help_text='True - с водяным знаком, False - без водяного знака', verbose_name='Водяной знак на PDF/XML'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_disk_space',
            field=models.PositiveIntegerField(default=50, verbose_name='Максимальное место на диске (МБ)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subscription_period',
            field=models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('quarter', '3 месяца'), ('half_year', '6 месяцев'), ('year', 'Год')], default='month', max_length=20, verbose_name='Период подписки'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='feature_advanced_analytics',
            field=models.BooleanField(default=False, verbose_name='Продвинутая аналитика'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='max_clients',
            field=models.PositiveIntegerField(default=5, help_text='0 означает неограниченное количество', verbose_name='Максимальное количество клиентов'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Базовый'), ('premium', 'Продвинутый')], default='basic', max_length=20, verbose_name='Тип тарифа'),
        ),
    ]
