# Generated by Django 5.2 on 2025-05-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pricingplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для подтверждения')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('token', models.CharField(blank=True, max_length=128, verbose_name='Токен подтверждения')),
                ('token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания токена')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение email',
                'verbose_name_plural': 'Подтверждения email',
            },
        ),
    ]
