# Generated by Django 5.2 on 2025-05-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.storagefolder', verbose_name='Родительская папка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_folders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Папка хранилища',
                'verbose_name_plural': 'Папки хранилища',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='storage_files/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение'), ('pdf', 'PDF'), ('archive', 'Архив'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Тип файла')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (в байтах)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.storagefolder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл хранилища',
                'verbose_name_plural': 'Файлы хранилища',
                'ordering': ['-updated_at'],
            },
        ),
    ]
