# Generated by Django 5.2 on 2025-04-28 20:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('issue_date', models.DateField(verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Наименование поставщика')),
                ('supplier_address', models.TextField(verbose_name='Адрес поставщика')),
                ('supplier_inn', models.CharField(max_length=15, verbose_name='ИНН поставщика')),
                ('supplier_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП поставщика')),
                ('supplier_bank', models.CharField(blank=True, max_length=200, verbose_name='Банк поставщика')),
                ('supplier_bank_account', models.CharField(blank=True, max_length=20, verbose_name='Р/с поставщика')),
                ('supplier_bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК банка поставщика')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма без налогов')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Скидка')),
                ('tax_rate', models.DecimalField(choices=[(Decimal('0.00'), 'Без НДС'), (Decimal('10.00'), '10%'), (Decimal('20.00'), '20%')], decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Сумма НДС')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Итого с налогами')),
                ('payment_info', models.TextField(blank=True, verbose_name='Информация об оплате')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование товара/услуги')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма')),
                ('vat_rate', models.DecimalField(choices=[(Decimal('0.00'), 'Без НДС'), (Decimal('10.00'), '10%'), (Decimal('20.00'), '20%')], decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Сумма НДС')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения')),
                ('customs_declaration', models.CharField(blank=True, max_length=100, verbose_name='Номер таможенной декларации')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Позиция счета',
                'verbose_name_plural': 'Позиции счета',
            },
        ),
    ]
