# Generated by Django 5.2 on 2025-04-29 16:14

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id'], 'verbose_name': 'Позиция счета', 'verbose_name_plural': 'Позиции счета'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='accountant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО главного бухгалтера'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_bank_corr_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корр. счет'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выставления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Сумма без НДС'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_bank',
            field=models.CharField(max_length=255, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_bank_account',
            field=models.CharField(max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_bank_bik',
            field=models.CharField(max_length=9, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_inn',
            field=models.CharField(max_length=20, verbose_name='ИНН поставщика'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_kpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП поставщика'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_name',
            field=models.CharField(max_length=255, verbose_name='Название поставщика'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='шт.', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
