# Generated by Django 5.2 on 2025-05-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_alter_invoiceitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН клиента'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], default='outgoing', max_length=10, verbose_name='Тип счета'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Детали оплаты'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо поставщика'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email поставщика'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон поставщика'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН поставщика (альт.)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
