# Generated by Django 5.2 on 2025-05-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_contact_email'),
        ('invoices', '0004_invoice_client_address_invoice_client_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='clients.client', verbose_name='Поставщик'),
        ),
    ]
