# Generated by Django 5.2 on 2025-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен'), ('new', 'Новый')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
