# Generated by Django 5.2 on 2025-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо'), ('business', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('name', models.CharField(max_length=200, verbose_name='Имя / Название организации')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('tax_id', models.CharField(blank=True, max_length=15, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Только для юр. лиц', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Название банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Банковский счет')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
