# Generated by Django 5.2 on 2025-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user_client_clients_cli_user_id_a8971a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entity_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('business', 'Юридическое лицо')], default='individual', max_length=20),
        ),
    ]
