# Generated by Django 5.2 on 2025-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_bank_corr_account_client_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email контактного лица'),
        ),
    ]
