# Generated by Django 5.2 on 2025-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='entity_type',
        ),
    ]
